name: YouTube Videos
on:
  push:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  youtube:
    name: Latest Videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          max_post_count: 10
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCkPSG_rUGJqAXmcajZ0mNMw"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$description</td></tr>$newline'
          description_max_length: 140
